name: Repository Dispatch
on:
  repository_dispatch:
    types: [deploy-again]
jobs:
  deploy-itself-again:
    uses: titaneric/yew-examples/.github/workflows/deploy.yml@main
    secrets:
      personal-token: ${{ secrets.PERSONAL_TOKEN }}